modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

# This is a URL to e.g. your GitHub or CurseForge issues page.
# It will appear in any crash reports this mod is directly involved in.
issueTrackerURL="https://github.com/baileyholl/ars-caelum/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader

[[mods]]
modId = "${mod_id}"
# The version number of the mod - unlike in the Forge MDK,
# we'll use the processResources task to replace this for us
version = "${mod_version}"
displayName = "${mod_name}"
# This will be displayed as your mod's logo in the Mods panel.
# logoFile="icon.png" #optional
# Some more fluff displayed in the Mods panel. Feel free to issue your special thanks here!
# credits="" #optional
# Some more fluff displayed in the Mods panel. Plug your stuff here!
authors="${mod_authors}" #optional
# A multi-line description for your mod. This has no minimum length, but it *is* required!
description = '''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

# Here's another dependency
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="patchouli"
mandatory=false
versionRange="[1.21-87,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="curios"
mandatory=true
versionRange="[1.21-9.0.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ars_nouveau"
mandatory=true
versionRange="[5.0.0,)"
ordering="AFTER"
side="BOTH"
